# Generated by Django 3.2.6 on 2021-12-29 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('validation_schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.validationschema')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('RC', 'Received')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IngressPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('RC', 'Received'), ('QV', 'Queued for validation'), ('VI', 'Validating'), ('VF', 'Validation failure'), ('VC', 'Validated'), ('QU', 'Queued for uploading'), ('UI', 'Uploading'), ('UF', 'Uploading failure'), ('UC', 'Uploaded')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('RP', 'Retrieve package'), ('UPD', 'Upload package to disk'), ('UPM', 'Upload package to MinIO'), ('SV', 'Start validation'), ('FV', 'Finalize validation'), ('CUG', 'Change user groups'), ('MID', 'Identify documents to migrate'), ('MSF', 'Start migration by id file'), ('MSD', 'Start migration by ISIS database'), ('MAC', 'Start migration by acronym'), ('MVY', 'Start migration by volume or year')], max_length=3)),
                ('status', models.CharField(choices=[('I', 'Initiated'), ('C', 'Completed'), ('F', 'Failed')], max_length=1)),
                ('annotation', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
